version: '3'
services:
  tigergraph:
    image: dbakereffendi/tigergraph:latest
    container_name: hello-tigergraph
    ports:
      - "14022:22"
      - "9000:9000"
      - "14240:14240"
    volumes:
      - ./gsql/tg_schema.gsql:/docker-entrypoint-initdb.d/tg_schema.gsql
      - ../gsql/tg_queries.gsql:/docker-entrypoint-initdb.d/tg_queries.gsql
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9000/query/social/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    stdin_open: true
    tty: true
